### ISSUE TITLE
BEAUti incorrectly using the default namespaces when importing alignment with custom template

### ISSUE THREAD

**Issue by bjoelle** [CompEvol/BeastFX#21]
I don't think this is a new problem but it's more annoying now that packages need to have their own separate namespace
When importing an alignment through `BeautiSubTemplate.createSubNet` (l362-364 in BeautiSubTemplate.java), BEAUti uses the default namespaces instead of the custom ones defined in the selected template
This causes the import to fail if the template relies on those namespaces, because the associated objects can't be found

**Comment by rbouckaert** [comment]
Good point, and indeed not a new problem but inherited from v2.6. 

Subtemplate namespaces are completely ignored, and any XML fragment is just copy/pasted into main-templates, where it uses the main-templates' namespaces. To handle subtemplate namesapaces will require managing the namespace of the main template while merging in sub-templates, which ideally manages removal of duplicates. Sub-template namespaces should be put after the main-template namespaces in order to keep the main template functional in case class names are duplicated.

Requires updating of `BeautiDoc.processTemplate()`.

**Comment by bjoelle** [comment]
Sorry for the trouble, but the bug still exists on the latest version (commit 33fd4f7) 
It seems to me that the alignment import actually doesn't use the namespaces from the template at all, but hardcoded namespaces which are written in `BeautiSubTemplate` l361-364

**Comment by rbouckaert** [comment]
You are right -- `BeautiSubTemplate` is not picking up the namespace, only the main template picks it up. I think [6b85401](https://github.com/CompEvol/BeastFX/commit/6b8540175fa0ec643e474905c3335cf97873527f) should fix that problem. Let me know if it still fails.

**Comment by bjoelle** [comment]
It works now, thanks !
