### ISSUE TITLE
More informative name?

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/BeastFX#8]
Would it possible to give this package a more informative name?  I'm not sure BeastFX means anything to non-Java people.  Why not something like Beast2GUI?

**Comment by rbouckaert** [comment]
Good point -- the BEAST package name is BEAST.app. There is also a github package [Compevol/BEAST.app](https://github.com/CompEvol/BEAST.app), which still contains the swing based applications, but is no  longer maintained (just to clarify the distinction between the names, and explaining the mess).

This repo contains CLI apps as well, so is not strictly GUI only.

Perhaps we should move `BeastFX` to `BEAST.app`, or rename `BEAST.app` to `BEAST.swing` and rename this to `BEAST.app` (if that is possible)?

**Comment by rbouckaert** [comment]
Reserving the `beast` namespace for `BEAST.base` makes sense. Any application in `BEAST.app` therefore has to have its own namespace, so that could be `beastapp`, but can just as well be `beastfx`. Changing the `beastfx` namespace seems to be more trouble than it is worth, since it means all dependent packages need to be updated as well. Maybe worth doing in a new major release.

Changing the `BeastFX` repository name to `BEAST.app` makes more sense though -- the BEAST package name for this repository is `BEAST.app` and there is some documentation that needs to be updated, but not much in terms of other dependencies.
